[package]
name = "sqlite"
version = "3.49.0"
nanvix-version = "0.12.435"

[builds]
[builds.matrix]
platforms = ["hyperlight", "microvm"]
modes = ["multi-process", "single-process", "standalone"]
memory = ["128mb", "256mb"]

[dependencies]
zlib = "1.3.1"
